id: 'republishBMWiXAway'
alias: 'L: BMW iX Away to MQTT'
trigger:
  platform: state
  entity_id: device_tracker.bmw_ix_e907
  to: 'not_home'
action:
  - service: mqtt.publish
    data_template:
      topic: 'location/car/bmw_ix_gps'
      retain: false
      payload:
              '
                  {"battery_level":100,
                  "longitude":0.0,
                  "latitude":0.0,
                  "gps_accuracy":100,
                  "tst": {{ as_timestamp(now()) | int }},
                  "_type":"location",
                  "tid":"sc"}
              '
