id: 'republishToyotaRav4Away'
alias: 'L: Toyota Rav4 Away to MQTT'
trigger:
  platform: state
  entity_id: device_tracker.toyota_rav4_ibeacon_tracker
  to: 'not_home'
action:
  - service: mqtt.publish
    data_template:
      topic: 'location/car/toyota_rav4_gps'
      retain: false
      payload:
              '
                  {"battery_level":100,
                  "longitude":0.0,
                  "latitude":0.0,
                  "gps_accuracy":100,
                  "tst": {{ as_timestamp(now()) | int }},
                  "_type":"location",
                  "tid":"sc"}
              '
