id: 'republishBMWiXHome'
alias: 'L: BMW iX Home to MQTT'
trigger:
  platform: state
  entity_id: device_tracker.bmw_ix_e907
  to: 'home'
action:
  - service: mqtt.publish
    data_template:
      topic: 'location/car/bmw_ix_gps'
      retain: false
      payload:
              '
                  {"battery_level":100,
                  "longitude":{{ states.zone.horizon_view.attributes.longitude }},
                  "latitude":{{ states.zone.horizon_view.attributes.latitude }},
                  "gps_accuracy":100,
                  "tst": {{ as_timestamp(now()) | int }},
                  "_type":"location",
                  "tid":"sc"}
              '
