- id: 'republishAudiA6Away'                                
  alias: 'audi_a6_away_to_mqtt'                            
  initial_state: 'on'                                      
  trigger:                                                 
    platform: state                                        
    entity_id: device_tracker.audi_a6_ibeacon_tracker
    to: 'not_home'                                         
  action:                                           
    - service: mqtt.publish             
      data_template:                      
        topic: 'location/car/audi_a6_gps'
        retain: false                        
        payload:                         
                '                        
                    {"battery_level":100,
                    "longitude":0.0,     
                    "latitude":0.0,      
                    "gps_accuracy":100,  
                    "tst": {{ as_timestamp(now()) | int }},                        
                    "_type":"location",                                          
                    "tid":"sc"}                            
                '                                          
                                                           
- id: 'republishAudiA6Home'                                
  alias: 'audi_a6_home_to_mqtt'                            
  initial_state: 'on'                                      
  trigger:                                                 
    platform: state                                        
    entity_id: device_tracker.audi_a6_ibeacon_tracker                   
    to: 'home'                          
  action:                               
    - service: mqtt.publish             
      data_template:                      
        topic: 'location/car/audi_a6_gps'
        retain: false                    
        payload:                                          
                '                                          
                    {"battery_level":100,           
                    "longitude":{{ states.zone.horizonview.attributes.longitude }},
                    "latitude":{{ states.zone.horizonview.attributes.latitude }},  
                    "gps_accuracy":100,                                            
                    "tst": {{ as_timestamp(now()) | int }},                        
                    "_type":"location",                                            
                    "tid":"sc"}                                                    
                '                                                                  

- id: 'republishAudiQ7Away'                                                                                                                 
  alias: 'audi_q7_away_to_mqtt'                                                                                                             
  initial_state: 'off'                                                                                                                       
  trigger:                                                                                                                                  
    platform: state                                                                                                                         
    entity_id: device_tracker.audi_q7_ibeacon_tracker                                                                                                    
    to: 'not_home'                                                                                                                          
  action:                                                                                                                                   
    - service: mqtt.publish                                                                                                                 
      data_template:                                                                                                                        
        topic: 'location/car/audi_q7_gps'                                                                                                   
        retain: false                                                                                                                       
        payload:                                                                                                                            
                '                                                                                                                           
                    {"battery_level":100,                                                                                                   
                    "longitude":0.0,                                                                                                        
                    "latitude":0.0,                                                                                                         
                    "gps_accuracy":100,                                                                                                     
                    "tst": {{ as_timestamp(now()) | int }},                                                                                 
                    "_type":"location",                                                                                                     
                    "tid":"sc"}                                                                                                             
                '                                                                                                                           
                                                                                                                                            
- id: 'republishAudiQ7Home'                                                                                                                 
  alias: 'audi_q7_home_to_mqtt'                                                                                                            
  initial_state: 'off'                                                                                                                       
  trigger:                                                                                                                                  
    platform: state                                                                                                                         
    entity_id: device_tracker.audi_q7_ibeacon_tracker                                                                                                    
    to: 'home'                                                                                                                              
  action:                                                                                                                                   
    - service: mqtt.publish                                                                                                                 
      data_template:                                                                                                                        
        topic: 'location/car/audi_q7_gps'                                                                                                   
        retain: false                                                                                                                       
        payload:                                                                                                                            
                '                                                                                                                           
                    {"battery_level":100,                                                                                                   
                    "longitude":{{ states.zone.horizonview.attributes.longitude }},                                                            
                    "latitude":{{ states.zone.horizonview.attributes.latitude }},                                                              
                    "gps_accuracy":100,                                                                                                     
                    "tst": {{ as_timestamp(now()) | int }},                                                                                 
                    "_type":"location",                                                                                                     
                    "tid":"sc"}                                                                                                             
                '                                                                                                                           
