- id: '1644898440052'
  alias: Stairs Pico On
  description: Raise/On button pressed on Stairs Pico
  trigger:
  - platform: device
    device_id: 7bfe7df82baff4d1d90b6dd8cd1c9a7c
    domain: lutron_caseta
    type: press
    subtype: 'on'
  condition: []
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.disable_stairs_cover_down_automation
  mode: single
- id: '1645033913099'
  alias: Retreat Pico On
  description: Raise/On button pressed on Retreat Pico
  trigger:
  - platform: device
    device_id: 70602769804d30452cd91fa3d2776165
    domain: lutron_caseta
    type: press
    subtype: 'on'
  condition: []
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.disable_retreat_cover_down_automation
  mode: single
- id: '1645034115630'
  alias: Livingroom Pico On
  description: Raise/On button pressed on Livingroom Pico
  trigger:
  - platform: device
    device_id: ffe90c1393bab182ceba5d98abef289e
    domain: lutron_caseta
    type: press
    subtype: 'on'
  condition: []
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.disable_livingroom_cover_down_automation
  mode: single
