# UPS Shutdown
- alias: "UPS based shutdown"
  initial_state: 'off'
  trigger:
    platform: numeric_state
    entity_id: sensor.closet_ups_battery_runtime
    below: 600
  action:
    - service: notify.telegram_horizonview
      data:
        message: "Home Assistant UPS shutdown"
    - service: hassio.host_shutdown

# Start actions
- id: 'startactions'
  alias: 'Start Actions'
  trigger:
    event: start
    platform: homeassistant
  condition: []
  action:
    # Send a telegram 
    - service: notify.telegram_horizonview
      data:
        message: "Home Assistant (re)started"
    - delay: 00:00:05
    # Restart the monitor services
    - service: mqtt.publish
      data:
        topic: "monitor/scan/restart"
        payload: ""

# Sonos Volume Reset - start the day at low volume
- id: 'sonosvolumereset'
  alias: "Sonos Volume Reset"
  trigger:
    platform: time
    at: '05:00:00'
  action:
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.dining_room, media_player.downstairs,
        media_player.family_room, media_player.kitchen_bar, 
        media_player.main_deck, media_player.retreat
      volume_level: 0.05

# Daily Pool temperature report
- id: 'dailypooltemp'
  alias: 'Daily Pool Temp report at 5am'
  trigger:
    platform: time
    at: '08:30:00'
  action:
    service: notify.telegram_horizonview # or telegram_bot.send_message
    data_template:
      message: "Pool Temperature {{ states('sensor.pentair_pooltemp') }}F"


# Test message      
- id: 'testmessage'
  alias: "Telegram Test command"
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/ping'
  action:
    service: notify.telegram_horizonview
    data:
      message: "pong"

# Reload message      
- id: 'reloadmessage'
  alias: "Home Assistant Reload command"
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/reload'
  action:
    - service: notify.telegram_horizonview
      data:                 
        message: "Reloading..."
    - service: frontend.reload_themes
                            
# Restart message           
- id: 'restartmessage'      
  alias: "Home Assistant Restart command"
  trigger:                  
    platform: event         
    event_type: telegram_command
    event_data:             
      command: '/restart'   
  action:                   
    - service: notify.telegram_horizonview
      data:                 
        message: "Restarting..."
    - service: homeassistant.restart
                            
# Reboot message            
- id: 'rebootmessage'       
  alias: "Home Assistant Reboot command"
  trigger:                  
    platform: event         
    event_type: telegram_command
    event_data:             
      command: '/reboot'    
  action:                   
    - service: notify.telegram_horizonview
      data:                 
        message: "Rebooting..."
    - service: hassio.host_reboot
