custom_header:
  compact_mode: true
title: Horizon View
views:
  - !include /config/lovelace/horizonview/views/home.yaml
  - !include /config/lovelace/horizonview/views/environment.yaml
  - !include /config/lovelace/horizonview/views/pool.yaml
#  - !include /config/lovelace/horizonview/views/media.yaml
  - !include /config/lovelace/horizonview/views/net_ops.yaml
  - !include /config/lovelace/horizonview/views/sensors.yaml

