custom_header:
  compact_mode: true
title: Horizon View
views:
  - !include /config/lovelace/horizonview/views/home.yaml
  - !include /config/lovelace/horizonview/views/weather.yaml
  - !include /config/lovelace/horizonview/views/environment.yaml
  - !include /config/lovelace/horizonview/views/alarm.yaml
  - !include /config/lovelace/horizonview/views/media.yaml
  - !include /config/lovelace/horizonview/views/cellar.yaml
  - !include /config/lovelace/horizonview/views/utilities.yaml
  - !include /config/lovelace/horizonview/views/appliances.yaml
#  - !include /config/lovelace/horizonview/views/greenhouse.yaml
#  - !include /config/lovelace/horizonview/views/hydrawise.yaml
#  - !include /config/lovelace/horizonview/views/pollen.yaml
  - !include /config/lovelace/horizonview/views/pool.yaml
  - !include /config/lovelace/horizonview/views/net_ops.yaml
#  - !include /config/lovelace/horizonview/views/nas.yaml
  - !include /config/lovelace/horizonview/views/tracking.yaml
  - !include /config/lovelace/horizonview/views/sensors.yaml
