# Pool Heater Reset - start the day with no heat
id: 'poolheaterreset'
alias: "A: Pool Heater Reset"
trigger:
  platform: time
  at: '05:00:00'
action:                                                                   
  - service: climate.turn_off
    target:
      entity_id: climate.pentair_0d_ce_47_pool_heat
