# Pool Report
id: 'poolreport'
alias: "N: Pool Report"
initial_state: 'on'
trigger:
  platform: event
  event_type: telegram_command
  event_data:
    command: '/pool'
action:
  - service: !secret telegram_notify
    data_template:
      message: > 
        Mode: {{states('climate.pentair_0d_ce_47_pool_heat')}}
         Set: {{state_attr('climate.pentair_0d_ce_47_pool_heat', 'temperature')}}F, 
         Now: {{state_attr('climate.pentair_0d_ce_47_pool_heat', 'current_temperature')}}F,
         Air: {{states('sensor.pentair_air_temperature')}}F
