# Pool Report
id: 'poolreport'
alias: "N: Pool Report"
initial_state: 'on'
trigger:
  platform: event
  event_type: telegram_command
  event_data:
    command: '/pool'
action:
  - service: !secret telegram_notify
    data_template:
      message: > 
        Pool: {{states('switch.pentair_0d_ce_47_pool')}}
         Spa: {{states('switch.pentair_0d_ce_47_spa')}}
        Jets: {{states('switch.pentair_0d_ce_47_jets')}}
        Fall: {{states('switch.pentair_0d_ce_47_waterfall')}},  
        Mode: {{states('climate.pentair_0d_ce_47_pool_heat')}},  
         Set: {{state_attr('climate.pentair_0d_ce_47_pool_heat', 'temperature')}}F, 
         Now: {{state_attr('climate.pentair_0d_ce_47_pool_heat', 'current_temperature')}}F,
         Air: {{states('sensor.pentair_0d_ce_47_air_temperature')}}F
