id: 'livingroomshadesupsunset'
alias: "A: Sunset Livingroom Shades Up"
trigger:
  platform: state
  entity_id: binary_sensor.all_shades_up
  from: "off"
  to: "on"
action:
  - service: scene.turn_on
    target:
      entity_id: scene.living_room_shades_up
