id: 'retreatshadeupsunset'
alias: "A: Sunset Retreat Shade Up"
trigger:
  platform: state
  entity_id: binary_sensor.all_shades_up
  from: "off"
  to: "on"
action:
  - service: scene.turn_on
    target:
      entity_id: scene.retreat_shade_up
