id: 'stairshadeupsunset'
alias: "A: Sunset Stairs Shade Up"
trigger:
  platform: state
  entity_id: binary_sensor.all_shades_up
  from: "off"
  to: "on"
action:
  - service: scene.turn_on
    target:
      entity_id: scene.stair_shade_up
