id: 'stairshadedownazimuth'
alias: "A: Sunrise Stairs Shade Down"
trigger:
  - platform: state
    entity_id: binary_sensor.all_shades_down
    from: "off"
    to: "on"
action:
  - service: scene.turn_on
    target:
      entity_id: scene.stair_shade_down
