# Check Garage doors
id: 'checkgaragedoors'
alias: "S: Check Garage Door"
trigger:
  platform: time
  at: '21:30:00'
condition:
  - condition: state
    entity_id: binary_sensor.main_garage_door
    state: "on"
action:
  - service: !secret telegram_notify
    data:
      message: "S: Main Garage Door is Open"
