id: 'hometoaway'
alias: "S: Switches to Away"
trigger:
  platform: state
  entity_id: sensor.vera_house_mode
condition:
  condition: and
  conditions:
    - condition: template
      value_template: '{{ trigger.from_state.state != "unavailable" }}'
    - condition: template
      value_template: '{{ trigger.to_state.state == "Away" }}'
    - condition: template
      value_template: "{{ trigger.from_state.state != trigger.to_state.state }}"
action:                                                                   
#  - service: scene.turn_on
#    target:
#      entity_id: scene.away
#  - service: climate.set_preset_mode
#    data_template:
#      entity_id: climate.main_floor
#      preset_mode: none
  - service: !secret telegram_notify
    data_template:
      message: "A: Away Scene"
