id: 'hometonight'
alias: "Lights, Switches to Night"
trigger:
  platform: state
  entity_id: sensor.vera_house_mode
condition:
  condition: and
  conditions:
    - condition: template
      value_template: '{{ trigger.from_state.state != "unavailable" }}'
    - condition: template
      value_template: '{{ trigger.to_state.state == "Night" }}'
    - condition: template
      value_template: "{{ trigger.from_state.state != trigger.to_state.state }}"
action:  
  - service: input_select.select_option
    target:
      entity_id: input_select.house_mode
    data:
      option: "Night"                                                                
  - service: scene.turn_on
    target:
      entity_id: scene.night
#  - service: climate.set_preset_mode
#    data_template:
#      entity_id: climate.main_floor
#      preset_mode: away
  - service: !secret telegram_notify
    data_template:
      message: "A: Night Scene"

