# Weather Report
id: 'weatherreport'
alias: "Weather Report"
trigger:
  platform: event
  event_type: telegram_command
  event_data:
    command: '/weather'
action:
  - service: !secret telegram_notify
    data:
      message: |
         Temperature: {{ states('sensor.gw1000_temp', with_unit=True) }}
         Feels  Like: {{ states('sensor.gw1000_feelslike', with_unit=True) }}
         Humidity: {{ states('sensor.gw1000_humidity', with_unit=True) }}
         Dewpoint: {{ states('sensor.gw1000_dewpoint', with_unit=True) }}
         {% if states('sensor.gw1000_temp') | float - states('sensor.gw1000_dewpoint') | float < 1.0 and states('ssensor.gw1000_humidity') | int > 95 %}         
         Fog possible!
         {% endif %}
