id: 'powergreenled'
alias: 'N: Power Green LED'
trigger:
  - platform: state
    entity_id: binary_sensor.familyroom_right_green_on
condition: 
  - condition: template 
    value_template: "{{ trigger.to_state.state != 'unavailable' }}" 
  - condition: template 
    value_template: "{{ trigger.to_state.state != 'unknown' }}" 
action:
  - service: >
      switch.turn_{{ trigger.to_state.state }}
    entity_id: switch.familyroom_right_green_led
