id: 'powergreenled'
alias: 'N: Power Green LED'
trigger:
  - platform: numeric_state
    entity_id: sensor.eagle_200_meter_power_demand
    # At least one of the following required
    below: -1
action:
  - service: switch.turn_on
    entity_id: switch.green_led
  - service: switch.turn_off
    entity_id: switch.yellow_led
  - service: switch.turn_off
    entity_id: switch.red_led
