# car zone state
id: 'carzone'
alias: 'Car Zone Change'
trigger:
  platform: state
  entity_id: device_tracker.audiq7_8ff5, device_tracker.426c7565_4368_6172_6d42_6561636f6e74_3838_4949_8ae8
condition:
  condition: and
  conditions:
    - condition: template
      value_template: '{{ trigger.from_state.state != "unavailable" }}'
    - condition: template
      value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"
action:
  service: !secret telegram_notify
  data_template:
    message: >
      {% if trigger.to_state.state == "not_home" %} 
        C: {{ trigger.to_state.name }} is away
      {% elif trigger.to_state.state == "home" %}
        C: {{ trigger.to_state.name }} is home
      {% endif %}

