# Help message      
id: 'helpmessage'
alias: "C: Telegram Help"
trigger:
  platform: event
  event_type: telegram_command
  event_data:
    command: '/help'
action:
  service: !secret telegram_notify
  data:
    title: "Commands:"
    message: |
      /hvac [climate entity] [off|on]
      /mode [home|away|night|vacation|status]
      /ping - request a test response.
      /reboot - reboot the HA host.
      /restart - restart the HA container.
      /status - request home status report.
      /pool - request pool status report.
      /weather - request a weather report.
      /usage - rolling 24hr internet usage.

