# Reboot message      
id: 'rebootmessage'
alias: "C: Home Assistant Reboot"
trigger:
  platform: event
  event_type: telegram_command
  event_data:
    command: '/reboot'
action:
  - service: !secret telegram_notify
    data:
      message: "Rebooting..."
  - service: hassio.host_reboot

