# Test message      
id: 'testmessage'
alias: "C: Telegram Test"
trigger:
  platform: event
  event_type: telegram_command
  event_data:
    command: '/ping'
action:
  service: !secret telegram_notify
  data_template:
    message: "pong"

