id: 'weeklybackup'         
alias: "S: Weekly Backup"
initial_state: 'on'
trigger:        
  platform: time
  at: '04:00:00'
condition:                   
- condition: time            
  weekday:                       
    - sat                          
action:                            
- service: hassio.backup_full
  data: {}
- service: !secret telegram_notify                  
  data_template:                                
    message: "Home Assistant backed up"
