# 36883ed7_remote_backup
id: 'weeklybackup'         
alias: "A: Weekly Snapshot"
initial_state: 'on'
trigger:        
  platform: time
  at: '04:00:00'
condition:                   
- condition: time            
  weekday:                       
    - sat                          
action:                            
- service: hassio.addon_start          
  data:                                
    addon: 36883ed7_remote_backup  
- service: !secret telegram_notify                  
  data_template:                                
    message: "Home Assistant backed up"
