id: 'aqara switch on'
alias: Aqara Inside Light Group On
trigger:
  - platform: mqtt
    topic: 'zigbee2mqtt/ZB Aqara Button1'
condition:
  - condition: template
    value_template: '{{ "hold" == trigger.payload_json.action }}'
action:
  - service: light.turn_on
    entity_id: light.all_inside_lights
  - service: !secret telegram_notify
    data_template:        
      message: "N: Aqara All Lights On"
