id: 'artlightson'
alias: "A: Art Lights On"
trigger:
  platform: sun
  event: sunset
  offset: '+00:30:00'
condition:
  condition: state
  entity_id: binary_sensor.both_away
  state: 'off'
action:
  service: scene.turn_on
  entity_id: scene.art_lights_on
