# Lights Notify
id: 'lightsnotify'
alias: "Lights Notify"
trigger:
  platform: state
  entity_id: switch.party_lights_84
condition:
  condition: and
  conditions:
    - condition: template
      value_template: '{{ trigger.from_state.state != "unavailable" }}'
    - condition: template
      value_template: '{{ trigger.to_state.state != "unavailable" }}'
    - condition: template
      value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"
action:
  service: !secret telegram_notify
  data_template:
    message: "N: {{ trigger.to_state.name }} is {{ trigger.to_state.state }}"
