# Xfinity Link Usage Report
id: 'wanusagereport'
alias: "N: WAN Usage Report"
trigger:
  platform: event
  event_type: telegram_command
  event_data:
    command: '/usage'
action:
  - service: !secret telegram_notify
    data_template:
      message: > 
       24 Hour WAN Usage: {{ states('sensor.xfinity_wan_statistics') | round(0) }} MiB
       Monthy WAN Usage: {{ states('sensor.xfinity_wan_usage_gb') | round(0) }} GiB
