esphome:
  name: familyroom-8118
  platform: ESP8266
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "75fe096998e1155acce851abbbb733e3"

wifi:
  ssid: "srp-horizonview"
  password: "kicker87"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Familyroom-8118 Fallback Hotspot"
    password: "An4M9FimrvgX"

captive_portal:

# Example configuration entry
web_server:

# Activates prometheus /metrics endpoint
prometheus:

# Example configuration entry
time:
  - platform: sntp
    id: sntp_time
    servers:
      - 192.168.35.157
      
i2c:
  sda: 4
  scl: 5
  scan: True

# Example configuration entry
sensor:
  - platform: hdc1080
    temperature:
      name: "Family Room Temperature"
      filters:
        - offset: -1.0
    humidity:
      name: "Family Room Humidity"
      filters:
        - offset: -15.0
    update_interval: 60s
  - platform: ccs811
    eco2:
      name: "Family Room eCO2"
      filters:
        - filter_out: 0
        - filter_out: 65021
    tvoc:
      name: "Family Room VOC"
      filters:
        - filter_out: 0
        - filter_out: 65021
    address: 0x5A
    baseline: 0x1674
    update_interval: 60s
