esphome:
  name: gameroom-680

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "5441f39603d4ccd8337698cc58bec690"

wifi:
  ssid: "srp-horizonview"
  password: "kicker87"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Gameroom-680 Fallback Hotspot"
    password: "3cknLWmpiBfP"

captive_portal:

# Example configuration entry
web_server:

# Activates prometheus /metrics endpoint
prometheus:

# Example configuration entry
time:
  - platform: sntp
    id: sntp_time
    servers:
      - 192.168.35.157

i2c:
  sda: 4
  scl: 5
  scan: True

bme680_bsec:
  address: 0x77
  
sensor:
  - platform: uptime
    name: Game Room 680 Uptime Second
    id: uptime_sensor
    update_interval: 60s
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
              int seconds = round(id(uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? String(days) + "d " : "") +
                (hours ? String(hours) + "h " : "") +
                (minutes ? String(minutes) + "m " : "") +
                (String(seconds) + "s")
              ).c_str();

  - platform: bme680_bsec
    temperature:
      name: "Game Room Temperature"
      id: game_room_temperature
    pressure:
      name: "Game Room Pressure"
      id: game_room_pressure
    humidity:
      name: "Game Room Humidity"
      id: game_room_humidity
    iaq:
      name: "Game Room IAQ"
    co2_equivalent:
      name: "Game Room eCO2"
    breath_voc_equivalent:
      name: "Game Room eVOC"

  - platform: template
    name: "Game Room DewPoint"
    id: game_room_dewpoint
    lambda: |-
      return (243.5*(log(id(game_room_humidity).state/100)+((17.67*id(game_room_temperature).state)/
      (243.5+id(game_room_temperature).state)))/(17.67-log(id(game_room_humidity).state/100)-
      ((17.67*id(game_room_temperature).state)/(243.5+id(game_room_temperature).state))));
    unit_of_measurement: °C
    update_interval: 60s
    icon: 'mdi:water-thermometer'

  - platform: wifi_signal
    name: "Game Room 680 WiFi Signal"
    update_interval: 60s

# Example configuration entry
button:
  - platform: restart
    name: "Game Room 680 Restart"

text_sensor:
  - platform: bme680_bsec
    iaq_accuracy:
      name: "Game Room IAQ Accuracy"
      
  - platform: template
    name: Game Room Comfort Level
    lambda: |-
      if (id(game_room_dewpoint).state > 23.9) {
        return {"Miserable"};
      } else if (id(game_room_dewpoint).state > 21.1) {
        return {"Oppresive"};
      } else if (id(game_room_dewpoint).state > 18.3) {
        return {"Uncomfortable"};
      } else if (id(game_room_dewpoint).state > 15.6) {
        return {"Sticky"};
      } else if (id(game_room_dewpoint).state > 12.8) {
        return {"Comfortable"};
      } else if (id(game_room_dewpoint).state > 10.0) {
        return {"Pleasant"};
      } else if (id(game_room_dewpoint).state > 0) {
        return {"Dry"};
      } else {
        return {"Undefined"};
      }
    icon: "mdi:water-percent"
    update_interval: 60s

  - platform: template
    name: Game Room 680 Uptime
    id: uptime_human
    icon: mdi:clock-start
