esphome:
  name: mancave-680
  platform: ESP8266
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "53faef08b9d5e762354a4afc7f8bd493"

wifi:
  ssid: "srp-horizonview"
  password: "kicker87"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Mancave-680 Fallback Hotspot"
    password: "K0ZyH5Se88PA"

captive_portal:

# Example configuration entry
web_server:

# Activates prometheus /metrics endpoint
prometheus:

# Example configuration entry
time:
  - platform: sntp
    id: sntp_time
    servers:
      - 192.168.35.157

i2c:
  sda: 4
  scl: 5
  scan: True

bme680_bsec:
  address: 0x77
  
sensor:
  - platform: uptime
    name: ManCave 680 Uptime Second
    id: uptime_sensor
    update_interval: 60s
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
              int seconds = round(id(uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? String(days) + "d " : "") +
                (hours ? String(hours) + "h " : "") +
                (minutes ? String(minutes) + "m " : "") +
                (String(seconds) + "s")
              ).c_str();

  - platform: bme680_bsec
    temperature:
      name: "ManCave Temperature"
      id: mancave_temperature
    pressure:
      name: "ManCave Pressure"
    humidity:
      name: "ManCave Humidity"
      id: mancave_humidity
    iaq:
      name: "ManCave IAQ"
    co2_equivalent:
      name: "ManCave eCO2"
    breath_voc_equivalent:
      name: "ManCave eVOC"

  - platform: template
    name: "ManCave DewPoint"
    id: mancave_dewpoint
    lambda: |-
      return (243.5*(log(id(mancave_humidity).state/100)+((17.67*id(mancave_temperature).state)/
      (243.5+id(mancave_temperature).state)))/(17.67-log(id(mancave_humidity).state/100)-
      ((17.67*id(mancave_temperature).state)/(243.5+id(mancave_temperature).state))));
    unit_of_measurement: °C
    update_interval: 60s
    icon: 'mdi:water-thermometer'

  - platform: wifi_signal
    name: "ManCave 680 WiFi Signal"
    update_interval: 60s

# Example configuration entry
button:
  - platform: restart
    name: "ManCave 680 Restart"

text_sensor:
  - platform: bme680_bsec
    iaq_accuracy:
      name: "ManCave IAQ Accuracy"
      
  - platform: template
    name: ManCave Comfort Level
    lambda: |-
      if (id(mancave_dewpoint).state > 23.9) {
        return {"Miserable"};
      } else if (id(mancave_dewpoint).state > 21.1) {
        return {"Oppresive"};
      } else if (id(mancave_dewpoint).state > 18.3) {
        return {"Uncomfortable"};
      } else if (id(mancave_dewpoint).state > 15.6) {
        return {"Sticky"};
      } else if (id(mancave_dewpoint).state > 12.8) {
        return {"Comfortable"};
      } else if (id(mancave_dewpoint).state > 10.0) {
        return {"Pleasant"};
      } else if (id(mancave_dewpoint).state > 0) {
        return {"Dry"};
      } else {
        return {"Undefined"};
      }
    icon: "mdi:water-percent"
    update_interval: 60s

  - platform: template
    name: ManCave 680 Uptime
    id: uptime_human
    icon: mdi:clock-start

