esphome:
  name: office-8118
  platform: ESP8266
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "1c839cc5fce75c8b9cf38847df300226"

wifi:
  ssid: "srp-horizonview"
  password: "kicker87"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Office-8118 Fallback Hotspot"
    password: "a7xSlsZYuWge"

captive_portal:

# Example configuration entry
web_server:

# Activates prometheus /metrics endpoint
prometheus:

# Example configuration entry
time:
  - platform: sntp
    id: sntp_time
    servers:
      - 192.168.35.157
      
i2c:
  sda: 4
  scl: 5
  scan: True

# Example configuration entry
sensor:
  - platform: hdc1080
    temperature:
      name: "Office Temperature"
      filters:
        - offset: -1.5
    humidity:
      name: "Office Humidity"
      filters:
        - offset: -10.0
    update_interval: 60s
  - platform: ccs811
    eco2:
      name: "Office eCO2"
      filters:
        - filter_out: 0
        - filter_out: 65021
    tvoc:
      name: "Office VOC"
      filters:
        - filter_out: 0
        - filter_out: 65021
    address: 0x5A
    baseline: 0x5481
    update_interval: 60s
