esphome:
  name: poolroom-11
  friendly_name: poolroom-11

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "vCf31oEmxDhrh9fq8ImRbkAv4qqBrzDSplDpAQ3qbAQ="

ota:
  password: "7d9574a5836eecae2182109cb13de380"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Poolroom-11 Fallback Hotspot"
    password: "quuHt6y9KSZp"

captive_portal:

# Example configuration entry
web_server:

# Activates prometheus /metrics endpoint
prometheus:

# Example configuration entry
time:
  - platform: sntp
    id: sntp_time
    servers:
      - 192.168.35.157

# Example configuration entry
sensor:
  - platform: dht
    pin: D2
    temperature:
      name: "Pool Room Temperature"
    humidity:
      name: "Pool Room Humidity"
    update_interval: 20s