external_components:
  - source: github://edenhaus/esphome@test-dallas
    components: [ dallas ]
    
esphome:
  name: pool-thermometer
  friendly_name: pool-thermometer

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "IZZeKpWT1xqZhGhjAOrvNuklzxFV7rLlHBBR+hmv08w="

ota:
  password: "2dc4c55563a4ea9036b27dc5c1425acc"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Pool-Thermometer"
    password: "Yd2WbSujlW3L"

captive_portal:

deep_sleep:
  run_duration: 90sec
  sleep_duration: 30min

# Example configuration entry
dallas:
  - pin: D6
    update_interval: 60s


sensor:
  - platform: adc
    pin: A0
    name: "Pool Sensor Battery Voltage"
    update_interval: 60s
    filters:
      - multiply: 4.20
  - platform: dallas
    index: 0
    name: "Pool Sensor Temperature"
    filters:
      - filter_out: NAN
  - platform: wifi_signal
    name: "Pool Sensor WiFi Signal"
    update_interval: 60s
 


